"""
Configuration and Master Catalog Definitions for MedIntel Synthetic Data Generation.
"""

from datetime import date

# Time horizon settings (12 months = 365 days)
SIMULATION_START_DATE = date(2025, 9, 1)
SIMULATION_DAYS = 365
SIMULATION_END_DATE = date(2026, 8, 31)

# Healthcare Locations (7 realistic facilities)
LOCATIONS_CATALOG = [
    {
        "location_id": "LOC001",
        "location_name": "Central Academic Medical Center",
        "location_type": "Academic Medical Center",
        "region": "Central Metro",
        "size_multiplier": 2.2,  # Large quaternary hospital with high surgical/ICU volume
        "base_activity_mean": 1.15,
    },
    {
        "location_id": "LOC002",
        "location_name": "North Suburban General Hospital",
        "location_type": "Community Hospital",
        "region": "North Suburban",
        "size_multiplier": 1.0,  # Standard community hospital
        "base_activity_mean": 1.00,
    },
    {
        "location_id": "LOC003",
        "location_name": "Metro Memorial Health - Main",
        "location_type": "General Hospital",
        "region": "Central Metro",
        "size_multiplier": 1.8,  # Large urban hospital
        "base_activity_mean": 1.10,
    },
    {
        "location_id": "LOC004",
        "location_name": "St. Jude Children's Pavilion",
        "location_type": "Children's Hospital",
        "region": "South Metro",
        "size_multiplier": 0.75,  # Pediatric specialty facility
        "base_activity_mean": 0.95,
    },
    {
        "location_id": "LOC005",
        "location_name": "Westside Community Hospital",
        "location_type": "Community Hospital",
        "region": "West Valley",
        "size_multiplier": 0.85,  # Moderate community hospital
        "base_activity_mean": 0.98,
    },
    {
        "location_id": "LOC006",
        "location_name": "Valley Regional Trauma Center",
        "location_type": "Trauma Center",
        "region": "West Valley",
        "size_multiplier": 1.5,  # High-volume acute trauma facility
        "base_activity_mean": 1.20,
    },
    {
        "location_id": "LOC007",
        "location_name": "South Ambulatory & Surgical Center",
        "location_type": "Ambulatory Surgical Center",
        "region": "South Metro",
        "size_multiplier": 0.5,  # Outpatient / Day surgery facility
        "base_activity_mean": 0.85,
    },
]

# Suppliers Master Catalog (15 synthetic pharma wholesalers & distributors)
SUPPLIERS_MASTER = [
    {
        "supplier_id": "SUP001",
        "supplier_name": "Apex Rx Distribution",
        "base_lead_time": 4,
        "base_reliability": 0.97,
        "specialties": ["Vasopressor / Inotrope", "General Anesthetic / Sedative", "Opioid Analgesic"],
    },
    {
        "supplier_id": "SUP002",
        "supplier_name": "Beacon Healthcare Supply",
        "base_lead_time": 5,
        "base_reliability": 0.95,
        "specialties": ["Antibiotic / Glycopeptide", "Cephalosporin", "Carbapenem", "Fluoroquinolone"],
    },
    {
        "supplier_id": "SUP003",
        "supplier_name": "CarePoint Logistics",
        "base_lead_time": 3,
        "base_reliability": 0.98,
        "specialties": ["Anticoagulant", "Cardiovascular / Antiarrhythmic", "Emergency / Resuscitation"],
    },
    {
        "supplier_id": "SUP004",
        "supplier_name": "DirectPharma Solutions",
        "base_lead_time": 6,
        "base_reliability": 0.92,
        "specialties": ["Electrolyte Solution", "Intravenous Fluids", "Corticosteroid"],
    },
    {
        "supplier_id": "SUP005",
        "supplier_name": "Evergreen Therapeutics Supply",
        "base_lead_time": 5,
        "base_reliability": 0.96,
        "specialties": ["Bronchodilator", "Antidiabetic / Insulin", "Antiemetic"],
    },
    {
        "supplier_id": "SUP006",
        "supplier_name": "Frontier Biologics",
        "base_lead_time": 7,
        "base_reliability": 0.91,
        "specialties": ["Biologics / Immunotherapy", "Oncology / Antineoplastic", "Thrombolytic"],
    },
    {
        "supplier_id": "SUP007",
        "supplier_name": "Genesis Prime Logistics",
        "base_lead_time": 4,
        "base_reliability": 0.94,
        "specialties": ["Neuromuscular Blocker", "Benzodiazepine", "Anticonvulsant"],
    },
    {
        "supplier_id": "SUP008",
        "supplier_name": "Horizon Medical Distribution",
        "base_lead_time": 5,
        "base_reliability": 0.89,
        "specialties": ["Antidiabetic / Insulin", "Endocrine", "Specialty Injectable"],
    },
    {
        "supplier_id": "SUP009",
        "supplier_name": "Integra MedSource",
        "base_lead_time": 4,
        "base_reliability": 0.96,
        "specialties": ["Antibiotic / Penicillin", "Antibiotic / Macrolide", "Antifungal"],
    },
    {
        "supplier_id": "SUP010",
        "supplier_name": "Junction Pharma Depot",
        "base_lead_time": 6,
        "base_reliability": 0.93,
        "specialties": ["Emergency / Resuscitation", "Cardiovascular / Antihypertensive"],
    },
    {
        "supplier_id": "SUP011",
        "supplier_name": "Kinetic Healthcare Logistics",
        "base_lead_time": 4,
        "base_reliability": 0.95,
        "specialties": ["Local Anesthetic", "General Anesthetic / Sedative"],
    },
    {
        "supplier_id": "SUP012",
        "supplier_name": "Luminary Rx Group",
        "base_lead_time": 5,
        "base_reliability": 0.94,
        "specialties": ["Gastrointestinal", "Electrolyte Solution", "Nutritional / Vitamin"],
    },
    {
        "supplier_id": "SUP013",
        "supplier_name": "MedVantage Distribution",
        "base_lead_time": 6,
        "base_reliability": 0.91,
        "specialties": ["Antiviral", "Immunosuppressive", "Antibiotic / Other"],
    },
    {
        "supplier_id": "SUP014",
        "supplier_name": "Nexus BioLogistics",
        "base_lead_time": 7,
        "base_reliability": 0.90,
        "specialties": ["Oncology / Antineoplastic", "Hematologic Agent", "Thrombolytic"],
    },
    {
        "supplier_id": "SUP015",
        "supplier_name": "OmniHealth Wholesalers",
        "base_lead_time": 3,
        "base_reliability": 0.98,
        "specialties": ["General Hospital Formulary", "Standard Fluids", "Common Analgesics"],
    },
]

# Medications Master Catalog (Exactly 75 realistic clinical medications)
MEDICATIONS_CATALOG = [
    # Critical Care / Vasopressors & Inotropes
    {
        "medication_id": "MED001",
        "generic_name": "Norepinephrine Bitartrate",
        "strength": "4 mg/4 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Vasopressor / Inotrope",
        "unit_cost": 14.50,
        "criticality": "High",
        "base_daily_usage_mean": 24,
        "demand_pattern": "surge_scenario",  # Scenario 1 target
    },
    {
        "medication_id": "MED002",
        "generic_name": "Epinephrine",
        "strength": "1 mg/mL (1:1000)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Emergency / Resuscitation",
        "unit_cost": 8.75,
        "criticality": "High",
        "base_daily_usage_mean": 18,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED003",
        "generic_name": "Vasopressin",
        "strength": "20 units/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Vasopressor / Inotrope",
        "unit_cost": 85.00,
        "criticality": "High",
        "base_daily_usage_mean": 8,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED004",
        "generic_name": "Dopamine Hydrochloride",
        "strength": "400 mg/250 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Vasopressor / Inotrope",
        "unit_cost": 22.00,
        "criticality": "High",
        "base_daily_usage_mean": 10,
        "demand_pattern": "gradual_decrease",
    },
    {
        "medication_id": "MED005",
        "generic_name": "Dobutamine Hydrochloride",
        "strength": "250 mg/250 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Vasopressor / Inotrope",
        "unit_cost": 24.50,
        "criticality": "High",
        "base_daily_usage_mean": 9,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED006",
        "generic_name": "Phenylephrine Hydrochloride",
        "strength": "10 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Vasopressor / Inotrope",
        "unit_cost": 12.20,
        "criticality": "High",
        "base_daily_usage_mean": 28,
        "demand_pattern": "stable",
    },

    # Anesthetics / Sedatives / Neuromuscular Blockers
    {
        "medication_id": "MED007",
        "generic_name": "Propofol",
        "strength": "10 mg/mL (100 mL)",
        "dosage_form": "Injectable Emulsion",
        "unit_of_measure": "vial",
        "therapeutic_class": "General Anesthetic / Sedative",
        "unit_cost": 18.90,
        "criticality": "High",
        "base_daily_usage_mean": 35,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED008",
        "generic_name": "Dexmedetomidine Hydrochloride",
        "strength": "200 mcg/2 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "General Anesthetic / Sedative",
        "unit_cost": 34.00,
        "criticality": "High",
        "base_daily_usage_mean": 16,
        "demand_pattern": "imbalance_scenario",  # Scenario 3 target
    },
    {
        "medication_id": "MED009",
        "generic_name": "Midazolam Hydrochloride",
        "strength": "5 mg/mL (2 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Benzodiazepine",
        "unit_cost": 4.25,
        "criticality": "Medium",
        "base_daily_usage_mean": 40,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED010",
        "generic_name": "Lorazepam",
        "strength": "2 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Benzodiazepine",
        "unit_cost": 5.10,
        "criticality": "Medium",
        "base_daily_usage_mean": 25,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED011",
        "generic_name": "Ketamine Hydrochloride",
        "strength": "50 mg/mL (10 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "General Anesthetic / Sedative",
        "unit_cost": 15.60,
        "criticality": "High",
        "base_daily_usage_mean": 12,
        "demand_pattern": "gradual_increase",
    },
    {
        "medication_id": "MED012",
        "generic_name": "Rocuronium Bromide",
        "strength": "10 mg/mL (5 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Neuromuscular Blocker",
        "unit_cost": 11.80,
        "criticality": "High",
        "base_daily_usage_mean": 20,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED013",
        "generic_name": "Vecuronium Bromide",
        "strength": "10 mg",
        "dosage_form": "Lyophilized Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Neuromuscular Blocker",
        "unit_cost": 14.20,
        "criticality": "High",
        "base_daily_usage_mean": 8,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED014",
        "generic_name": "Cisatracurium Besylate",
        "strength": "2 mg/mL (10 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Neuromuscular Blocker",
        "unit_cost": 29.50,
        "criticality": "High",
        "base_daily_usage_mean": 11,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED015",
        "generic_name": "Etomidate",
        "strength": "2 mg/mL (10 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "General Anesthetic / Sedative",
        "unit_cost": 9.40,
        "criticality": "High",
        "base_daily_usage_mean": 14,
        "demand_pattern": "stable",
    },

    # Analgesics & Opioids
    {
        "medication_id": "MED016",
        "generic_name": "Fentanyl Citrate",
        "strength": "100 mcg/2 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "ampule",
        "therapeutic_class": "Opioid Analgesic",
        "unit_cost": 3.80,
        "criticality": "High",
        "base_daily_usage_mean": 60,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED017",
        "generic_name": "Hydromorphone Hydrochloride",
        "strength": "2 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Opioid Analgesic",
        "unit_cost": 4.50,
        "criticality": "High",
        "base_daily_usage_mean": 38,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED018",
        "generic_name": "Morphine Sulfate",
        "strength": "4 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Opioid Analgesic",
        "unit_cost": 3.20,
        "criticality": "High",
        "base_daily_usage_mean": 45,
        "demand_pattern": "gradual_decrease",
    },
    {
        "medication_id": "MED019",
        "generic_name": "Acetaminophen IV",
        "strength": "1000 mg/100 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "vial",
        "therapeutic_class": "Non-Opioid Analgesic",
        "unit_cost": 32.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 30,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED020",
        "generic_name": "Ketorolac Tromethamine",
        "strength": "30 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "NSAID",
        "unit_cost": 2.90,
        "criticality": "Medium",
        "base_daily_usage_mean": 26,
        "demand_pattern": "stable",
    },

    # Antimicrobials / Antibiotics / Antifungals / Antivirals
    {
        "medication_id": "MED021",
        "generic_name": "Vancomycin Hydrochloride",
        "strength": "1 g",
        "dosage_form": "Lyophilized Powder for IV",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antibiotic / Glycopeptide",
        "unit_cost": 8.50,
        "criticality": "High",
        "base_daily_usage_mean": 42,
        "demand_pattern": "false_alarm_scenario",  # Scenario 6 target
    },
    {
        "medication_id": "MED022",
        "generic_name": "Meropenem",
        "strength": "1 g",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Carbapenem",
        "unit_cost": 21.00,
        "criticality": "High",
        "base_daily_usage_mean": 25,
        "demand_pattern": "emerging_risk_scenario",  # Scenario 2 target
    },
    {
        "medication_id": "MED023",
        "generic_name": "Cefepime Hydrochloride",
        "strength": "2 g",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cephalosporin",
        "unit_cost": 16.50,
        "criticality": "High",
        "base_daily_usage_mean": 32,
        "demand_pattern": "seasonal_winter",
    },
    {
        "medication_id": "MED024",
        "generic_name": "Piperacillin and Tazobactam",
        "strength": "4.5 g",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antibiotic / Penicillin",
        "unit_cost": 19.80,
        "criticality": "High",
        "base_daily_usage_mean": 48,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED025",
        "generic_name": "Ceftriaxone Sodium",
        "strength": "1 g",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cephalosporin",
        "unit_cost": 6.20,
        "criticality": "Medium",
        "base_daily_usage_mean": 55,
        "demand_pattern": "seasonal_winter",
    },
    {
        "medication_id": "MED026",
        "generic_name": "Cefazolin Sodium",
        "strength": "2 g",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cephalosporin",
        "unit_cost": 5.40,
        "criticality": "Medium",
        "base_daily_usage_mean": 65,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED027",
        "generic_name": "Azithromycin IV",
        "strength": "500 mg",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antibiotic / Macrolide",
        "unit_cost": 11.50,
        "criticality": "Medium",
        "base_daily_usage_mean": 22,
        "demand_pattern": "seasonal_winter",
    },
    {
        "medication_id": "MED028",
        "generic_name": "Levofloxacin",
        "strength": "500 mg/100 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Fluoroquinolone",
        "unit_cost": 14.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 19,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED029",
        "generic_name": "Daptomycin",
        "strength": "500 mg",
        "dosage_form": "Lyophilized Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antibiotic / Lipopeptide",
        "unit_cost": 145.00,
        "criticality": "High",
        "base_daily_usage_mean": 7,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED030",
        "generic_name": "Linezolid",
        "strength": "600 mg/300 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Antibiotic / Oxazolidinone",
        "unit_cost": 58.00,
        "criticality": "High",
        "base_daily_usage_mean": 6,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED031",
        "generic_name": "Metronidazole",
        "strength": "500 mg/100 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Antibacterial / Antiprotozoal",
        "unit_cost": 4.80,
        "criticality": "Medium",
        "base_daily_usage_mean": 33,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED032",
        "generic_name": "Fluconazole",
        "strength": "200 mg/100 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Antifungal",
        "unit_cost": 13.50,
        "criticality": "Medium",
        "base_daily_usage_mean": 15,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED033",
        "generic_name": "Micafungin Sodium",
        "strength": "100 mg",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antifungal / Echinocandin",
        "unit_cost": 165.00,
        "criticality": "High",
        "base_daily_usage_mean": 5,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED034",
        "generic_name": "Acyclovir Sodium",
        "strength": "500 mg",
        "dosage_form": "Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antiviral",
        "unit_cost": 28.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 9,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED035",
        "generic_name": "Amikacin Sulfate",
        "strength": "500 mg/2 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antibiotic / Aminoglycoside",
        "unit_cost": 17.50,
        "criticality": "Medium",
        "base_daily_usage_mean": 6,
        "demand_pattern": "stable",
    },

    # Anticoagulants & Hematologic Agents
    {
        "medication_id": "MED036",
        "generic_name": "Heparin Sodium",
        "strength": "5000 units/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Anticoagulant",
        "unit_cost": 9.20,
        "criticality": "High",
        "base_daily_usage_mean": 50,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED037",
        "generic_name": "Enoxaparin Sodium",
        "strength": "40 mg/0.4 mL",
        "dosage_form": "Prefilled Syringe",
        "unit_of_measure": "syringe",
        "therapeutic_class": "Anticoagulant / LMWH",
        "unit_cost": 18.40,
        "criticality": "High",
        "base_daily_usage_mean": 62,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED038",
        "generic_name": "Bivalirudin",
        "strength": "250 mg",
        "dosage_form": "Lyophilized Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Anticoagulant / Direct Thrombin Inhibitor",
        "unit_cost": 280.00,
        "criticality": "High",
        "base_daily_usage_mean": 3,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED039",
        "generic_name": "Alteplase (tPA)",
        "strength": "100 mg",
        "dosage_form": "Lyophilized Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Thrombolytic",
        "unit_cost": 3100.00,
        "criticality": "High",
        "base_daily_usage_mean": 2,
        "demand_pattern": "expiry_scenario",  # Scenario 4 target
    },
    {
        "medication_id": "MED040",
        "generic_name": "Protamine Sulfate",
        "strength": "10 mg/mL (5 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antidote / Heparin Reversal",
        "unit_cost": 35.00,
        "criticality": "High",
        "base_daily_usage_mean": 4,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED041",
        "generic_name": "Phytonadione (Vitamin K1)",
        "strength": "10 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "ampule",
        "therapeutic_class": "Hematologic / Hemostatic",
        "unit_cost": 84.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 5,
        "demand_pattern": "stable",
    },

    # Cardiovascular / Antiarrhythmics / Antihypertensives
    {
        "medication_id": "MED042",
        "generic_name": "Amiodarone Hydrochloride",
        "strength": "150 mg/3 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "ampule",
        "therapeutic_class": "Cardiovascular / Antiarrhythmic",
        "unit_cost": 7.60,
        "criticality": "High",
        "base_daily_usage_mean": 18,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED043",
        "generic_name": "Adenosine",
        "strength": "6 mg/2 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cardiovascular / Antiarrhythmic",
        "unit_cost": 22.50,
        "criticality": "High",
        "base_daily_usage_mean": 6,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED044",
        "generic_name": "Nicardipine Hydrochloride",
        "strength": "25 mg/10 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cardiovascular / Antihypertensive",
        "unit_cost": 46.00,
        "criticality": "High",
        "base_daily_usage_mean": 14,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED045",
        "generic_name": "Labetalol Hydrochloride",
        "strength": "5 mg/mL (20 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cardiovascular / Beta-Blocker",
        "unit_cost": 16.20,
        "criticality": "High",
        "base_daily_usage_mean": 21,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED046",
        "generic_name": "Metoprolol Tartrate IV",
        "strength": "5 mg/5 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cardiovascular / Beta-Blocker",
        "unit_cost": 6.80,
        "criticality": "Medium",
        "base_daily_usage_mean": 28,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED047",
        "generic_name": "Diltiazem Hydrochloride",
        "strength": "25 mg/5 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Cardiovascular / Calcium Channel Blocker",
        "unit_cost": 12.40,
        "criticality": "Medium",
        "base_daily_usage_mean": 17,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED048",
        "generic_name": "Nitroglycerin IV",
        "strength": "50 mg/250 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Cardiovascular / Vasodilator",
        "unit_cost": 31.00,
        "criticality": "High",
        "base_daily_usage_mean": 11,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED049",
        "generic_name": "Furosemide",
        "strength": "40 mg/4 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Diuretic",
        "unit_cost": 2.10,
        "criticality": "Medium",
        "base_daily_usage_mean": 58,
        "demand_pattern": "stable",
    },

    # Respiratory & Emergency
    {
        "medication_id": "MED050",
        "generic_name": "Albuterol Sulfate",
        "strength": "2.5 mg/3 mL",
        "dosage_form": "Inhalation Solution",
        "unit_of_measure": "nebule",
        "therapeutic_class": "Bronchodilator",
        "unit_cost": 0.95,
        "criticality": "Medium",
        "base_daily_usage_mean": 75,
        "demand_pattern": "seasonal_winter",
    },
    {
        "medication_id": "MED051",
        "generic_name": "Ipratropium Bromide",
        "strength": "0.5 mg/2.5 mL",
        "dosage_form": "Inhalation Solution",
        "unit_of_measure": "nebule",
        "therapeutic_class": "Bronchodilator / Anticholinergic",
        "unit_cost": 1.40,
        "criticality": "Medium",
        "base_daily_usage_mean": 52,
        "demand_pattern": "seasonal_winter",
    },
    {
        "medication_id": "MED052",
        "generic_name": "Naloxone Hydrochloride",
        "strength": "0.4 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antidote / Opioid Antagonist",
        "unit_cost": 16.00,
        "criticality": "High",
        "base_daily_usage_mean": 10,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED053",
        "generic_name": "Atropine Sulfate",
        "strength": "1 mg/10 mL",
        "dosage_form": "Prefilled Syringe",
        "unit_of_measure": "syringe",
        "therapeutic_class": "Emergency / Resuscitation",
        "unit_cost": 14.50,
        "criticality": "High",
        "base_daily_usage_mean": 8,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED054",
        "generic_name": "Calcium Chloride",
        "strength": "1000 mg/10 mL (10%)",
        "dosage_form": "Prefilled Syringe",
        "unit_of_measure": "syringe",
        "therapeutic_class": "Electrolyte Solution / Resuscitation",
        "unit_cost": 18.00,
        "criticality": "High",
        "base_daily_usage_mean": 9,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED055",
        "generic_name": "Sodium Bicarbonate",
        "strength": "8.4% (50 mEq/50 mL)",
        "dosage_form": "Prefilled Syringe",
        "unit_of_measure": "syringe",
        "therapeutic_class": "Electrolyte Solution / Resuscitation",
        "unit_cost": 15.50,
        "criticality": "High",
        "base_daily_usage_mean": 24,
        "demand_pattern": "stable",
    },

    # Endocrine & Metabolism
    {
        "medication_id": "MED056",
        "generic_name": "Insulin Regular Human",
        "strength": "100 units/mL (10 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antidiabetic / Insulin",
        "unit_cost": 42.00,
        "criticality": "High",
        "base_daily_usage_mean": 22,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED057",
        "generic_name": "Insulin Glargine",
        "strength": "100 units/mL (10 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antidiabetic / Insulin",
        "unit_cost": 98.00,
        "criticality": "High",
        "base_daily_usage_mean": 18,
        "demand_pattern": "supplier_leadtime_scenario",  # Scenario 5 target
    },
    {
        "medication_id": "MED058",
        "generic_name": "Insulin Lispro",
        "strength": "100 units/mL (10 mL)",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antidiabetic / Insulin",
        "unit_cost": 88.00,
        "criticality": "High",
        "base_daily_usage_mean": 20,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED059",
        "generic_name": "Dextrose 50%",
        "strength": "25 g/50 mL",
        "dosage_form": "Prefilled Syringe",
        "unit_of_measure": "syringe",
        "therapeutic_class": "Hypoglycemia Emergency",
        "unit_cost": 12.80,
        "criticality": "High",
        "base_daily_usage_mean": 15,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED060",
        "generic_name": "Glucagon",
        "strength": "1 mg",
        "dosage_form": "Lyophilized Powder with Diluent",
        "unit_of_measure": "kit",
        "therapeutic_class": "Hypoglycemia Emergency",
        "unit_cost": 175.00,
        "criticality": "High",
        "base_daily_usage_mean": 2,
        "demand_pattern": "stable",
    },

    # Corticosteroids & Antiemetics
    {
        "medication_id": "MED061",
        "generic_name": "Methylprednisolone Sodium Succinate",
        "strength": "125 mg",
        "dosage_form": "Lyophilized Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Corticosteroid",
        "unit_cost": 14.20,
        "criticality": "Medium",
        "base_daily_usage_mean": 26,
        "demand_pattern": "seasonal_winter",
    },
    {
        "medication_id": "MED062",
        "generic_name": "Dexamethasone Sodium Phosphate",
        "strength": "4 mg/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Corticosteroid",
        "unit_cost": 3.60,
        "criticality": "Medium",
        "base_daily_usage_mean": 36,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED063",
        "generic_name": "Hydrocortisone Sodium Succinate",
        "strength": "100 mg",
        "dosage_form": "Lyophilized Powder for Injection",
        "unit_of_measure": "vial",
        "therapeutic_class": "Corticosteroid",
        "unit_cost": 8.90,
        "criticality": "Medium",
        "base_daily_usage_mean": 14,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED064",
        "generic_name": "Ondansetron Hydrochloride",
        "strength": "4 mg/2 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antiemetic",
        "unit_cost": 2.40,
        "criticality": "Medium",
        "base_daily_usage_mean": 68,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED065",
        "generic_name": "Metoclopramide Hydrochloride",
        "strength": "10 mg/2 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Antiemetic / Prokinetic",
        "unit_cost": 3.10,
        "criticality": "Low",
        "base_daily_usage_mean": 20,
        "demand_pattern": "stable",
    },

    # Fluids & Electrolytes
    {
        "medication_id": "MED066",
        "generic_name": "Potassium Chloride",
        "strength": "20 mEq/100 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Electrolyte Solution",
        "unit_cost": 8.20,
        "criticality": "High",
        "base_daily_usage_mean": 35,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED067",
        "generic_name": "Magnesium Sulfate",
        "strength": "2 g/50 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Electrolyte Solution",
        "unit_cost": 7.50,
        "criticality": "Medium",
        "base_daily_usage_mean": 28,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED068",
        "generic_name": "Sodium Chloride 0.9%",
        "strength": "1000 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Intravenous Fluids",
        "unit_cost": 2.80,
        "criticality": "High",
        "base_daily_usage_mean": 120,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED069",
        "generic_name": "Lactated Ringer's Solution",
        "strength": "1000 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "bag",
        "therapeutic_class": "Intravenous Fluids",
        "unit_cost": 3.20,
        "criticality": "High",
        "base_daily_usage_mean": 95,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED070",
        "generic_name": "Albumin Human 25%",
        "strength": "12.5 g/50 mL",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "vial",
        "therapeutic_class": "Plasma Volume Expander",
        "unit_cost": 65.00,
        "criticality": "High",
        "base_daily_usage_mean": 15,
        "demand_pattern": "stable",
    },

    # Oncology & Specialty Biologics
    {
        "medication_id": "MED071",
        "generic_name": "Paclitaxel",
        "strength": "100 mg/16.7 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Oncology / Antineoplastic",
        "unit_cost": 120.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 4,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED072",
        "generic_name": "Rituximab",
        "strength": "500 mg/50 mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "vial",
        "therapeutic_class": "Biologics / Immunotherapy",
        "unit_cost": 890.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 2,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED073",
        "generic_name": "Filgrastim (G-CSF)",
        "strength": "300 mcg/0.5 mL",
        "dosage_form": "Prefilled Syringe",
        "unit_of_measure": "syringe",
        "therapeutic_class": "Hematologic / Colony-Stimulating Factor",
        "unit_cost": 215.00,
        "criticality": "Medium",
        "base_daily_usage_mean": 6,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED074",
        "generic_name": "Immune Globulin IV (IVIG)",
        "strength": "10 g/100 mL (10%)",
        "dosage_form": "IV Infusion",
        "unit_of_measure": "vial",
        "therapeutic_class": "Biologics / Immunotherapy",
        "unit_cost": 950.00,
        "criticality": "High",
        "base_daily_usage_mean": 3,
        "demand_pattern": "stable",
    },
    {
        "medication_id": "MED075",
        "generic_name": "Oxytocin",
        "strength": "10 units/mL",
        "dosage_form": "Injectable Solution",
        "unit_of_measure": "ampule",
        "therapeutic_class": "Obstetric / Labor Induction",
        "unit_cost": 6.50,
        "criticality": "High",
        "base_daily_usage_mean": 22,
        "demand_pattern": "stable",
    },
]

# Scenario Definitions for Ground Truth & Injection
SCENARIO_DEFINITIONS = [
    {
        "scenario_id": "SCENARIO-1",
        "medication_id": "MED001",  # Norepinephrine Bitartrate 4 mg/4 mL
        "location_id": "LOC006",    # Valley Regional Trauma Center
        "expected_issue": "Surging ICU/trauma utilization combined with active primary supplier disruption causing imminent stockout in 48-72 hours.",
        "expected_severity": "CRITICAL",
        "expected_stockout_window": "2-3 days",
        "expected_recommendation": "Declare acute critical shortage, expedite secondary supplier emergency PO, and execute urgent stock transfer of 150 vials from Central AMC (LOC001).",
    },
    {
        "scenario_id": "SCENARIO-2",
        "medication_id": "MED022",  # Meropenem 1 g
        "location_id": "LOC002",    # North Suburban General Hospital
        "expected_issue": "Accelerating burn rate from septic patient admissions; inventory currently exceeds static reorder threshold but will breach buffer in ~7 days without reorder acceleration.",
        "expected_severity": "MEDIUM",
        "expected_stockout_window": "7-10 days",
        "expected_recommendation": "Classify as emerging risk; dynamically adjust safety stock baseline upwards and trigger automated replenishment PO 5 days ahead of schedule.",
    },
    {
        "scenario_id": "SCENARIO-3",
        "medication_id": "MED008",  # Dexmedetomidine HCl 200 mcg/2 mL
        "location_id": "LOC005",    # Westside Community Hospital (Deficit) vs LOC001 (Surplus)
        "secondary_location_id": "LOC001",
        "expected_issue": "Inter-facility inventory imbalance: LOC005 has 1.8 days of supply while LOC001 holds an excessive 62 days of supply.",
        "expected_severity": "HIGH",
        "expected_stockout_window": "2 days",
        "expected_recommendation": "Rebalance regional network: initiate lateral transfer of 200 vials from Central AMC (LOC001) to Westside Community (LOC005) immediately.",
    },
    {
        "scenario_id": "SCENARIO-4",
        "medication_id": "MED039",  # Alteplase (tPA) 100 mg
        "location_id": "LOC007",    # South Ambulatory & Surgical Center
        "secondary_location_id": "LOC003",
        "expected_issue": "Substantial quantity (280 vials, $868k value) of near-expiry lot at low-velocity outpatient center with expiration in 35 days and ~250 days of local supply.",
        "expected_severity": "HIGH",
        "expected_stockout_window": "None (Expiration/Waste Risk)",
        "expected_recommendation": "Prevent high-cost drug write-off: transfer 250 expiring vials to high-volume comprehensive stroke center at Metro Memorial (LOC003) for prioritized FIFO utilization.",
    },
    {
        "scenario_id": "SCENARIO-5",
        "medication_id": "MED057",  # Insulin Glargine 100 units/mL
        "location_id": "LOC003",    # Metro Memorial Health - Main
        "supplier_id": "SUP008",    # Horizon Medical Distribution
        "expected_issue": "Upstream supplier lead-time surge from 5 days to 25 days due to packaging line failure, rendering on-hand buffer (12 days) insufficient.",
        "expected_severity": "HIGH",
        "expected_stockout_window": "12-14 days",
        "expected_recommendation": "Reroute purchase order allocation to alternate certified vendor (SUP005) with 5-day lead time to avoid stockout.",
    },
    {
        "scenario_id": "SCENARIO-6",
        "medication_id": "MED021",  # Vancomycin HCl 1 g
        "location_id": "LOC004",    # St. Jude Children's Pavilion
        "expected_issue": "False alarm mitigation: on-hand inventory is low (2.1 days) but confirmed inbound purchase order PO-10882 is in transit arriving within 24 hours.",
        "expected_severity": "LOW",
        "expected_stockout_window": "Protected (Inbound PO Arrival)",
        "expected_recommendation": "No escalation required; inbound shipment confirmed on schedule with carrier tracking. Maintain standard monitoring.",
    },
]
