"""
Gemini Copilot chat and conversational investigation schemas for MedIntel API.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Chat message in conversation."""
    role: str = Field(..., description="Role: 'user', 'model', or 'assistant'")
    content: str = Field(..., description="Message text content")


class ChatRequest(BaseModel):
    """User query request for MedIntel Copilot."""
    prompt: str = Field(..., description="Natural language question or prompt")
    conversation_history: List[ChatMessage] = Field(default_factory=list, description="Recent conversation turns")
    focused_medication_id: Optional[str] = Field(None, description="Optional medication ID currently viewed in UI")
    focused_location_id: Optional[str] = Field(None, description="Optional location ID currently viewed in UI")
    context_medication_id: Optional[str] = Field(None, description="Last mentioned medication ID in conversation")


class ToolCallRecord(BaseModel):
    """Record of a tool/function executed during Copilot reasoning."""
    tool_name: str
    arguments: Dict[str, Any]
    result_summary: str


class ChatResponse(BaseModel):
    """Grounded Copilot response."""
    response: str = Field(..., description="Markdown-formatted grounded assistant response")
    tools_used: List[ToolCallRecord] = Field(default_factory=list, description="Application tools invoked to retrieve facts")
    suggested_followups: List[str] = Field(default_factory=list, description="Contextual suggested questions")
    is_fallback: bool = Field(False, description="True if generated by local deterministic fallback rather than live Gemini API")
    mentioned_medication_id: Optional[str] = Field(None, description="Medication ID focused or mentioned in this response")
